platform: linux
image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: 2.7-alpine
inputs:
- name: dependabot-core.git
run:
  path: /bin/sh
  args:
  - -c
  - |
      set -ex
      apk update && \
      apk add --no-cache \
        g++ \
        libxslt-dev \
        libxml2-dev \
        make && \
        gem update --system && \
        gem install bundler --no-document

      bundle config build.nokogiri --use-system-libraries
      bundle config set path '../../requirements'
      cd dependabot-core.git/docker
      bundle install
      bundle exec rspec ./spec/
      bundle exec rubocop ../
